export enum ROUTE_PATHS {
    HOME = "/",
    GET_STARTED = "get-started",
    ACCORDION = "accordion",
    ALERT = "alert",
    AVATAR = "avatar",
    BADGE = "badge",
    CARD = "card",
    CHECKBOX = "checkbox",
    DIALOG = "dialog",
    DROPDOWN = "dropdown",
    INPUT = "input",
    NAVBAR = "navbar",
    SELECT = "select",
    SIDEBAR = "sidebar",
    TABS = "tabs",
    TEXTAREA = "textarea",
    TOOLTIP = "tooltip",
    ABOUT_ME = "about-me"
}